### ISSUE TITLE
Add plugin.info.txt and move files to root of repository

### ISSUE THREAD

**Issue by lupo49** [TomCafferty/plugin-table2csv#1]
Hi,

could you please add a plugin.info.txt to the git repo and move the files out of the "plugin-table2csv" directory? Then the user could install it the plugin through the DokuWiki plugin manager.

Thanks!

**Comment by TomCafferty** [comment]
Hi,
I moved the files to the root and added the plugin.info.txt.  
Thanks for the changes.

**Comment by TomCafferty** [comment]
Hi,

I was going thru my GitHub repositories and see that I made a copy of your configured plugin of plugin-sql. I don't think I ever informed you.  

The changes are 
- expose the table id so I could use it for my tableplot plugin.  
- added the ability to get table headings from enumerated database fields.  
- added ability to sort the table by selecting column headings.

I have attached 2 screenshots of an example of what item 2 in this list provides.  The original sql would give me a table of repeated rows when querying an enumerated field.  With the change I can specify to use the enumerated field as table headings and get the 2nd screen shot. 

The updated code is at https://github.com/TomCafferty/plugin-sql [1] We can leave these separate or you can merge with yours. See what you think.  If you want me to make changes to my code also just let me know. 

The code contains an example if you want to try it out. An udateREADME.txt file lists the new parameters. All changes should be backwards compatible. 

Regards
Tom

## Links:

[1] https://github.com/TomCafferty/plugin-sql%20
